### ISSUE TITLE
Feature request: read JWT from stdin

### ISSUE THREAD

**Issue by manishtomar** [mike-engel/jwt-cli#10]
### Summary
Please provide an option like `-` that allows one to to decode jwt from stdin. For example following usecase will be helpful
```
curl https://some-login-call | jq .token | jwt decode -
```

**Comment by mike-engel** [comment]
Hey @manishtomar, thanks for the suggestion! I've added support for `stdin` on both `encode` and `decode` with 7058cb7.

It should be published to homebrew and github releases soon, and then I'll close this issue 😄
