### ISSUE TITLE
Array for values in payload

### ISSUE THREAD

**Issue by fhuonder** [mike-engel/jwt-cli#101]
Hi,

It would be greate if arrays of values could be passed. E.g. aud can be an array.
The same should apply for custom payload attributes.

Regards,
Florain

**Comment by mike-engel** [comment]
Hi @fhuonder! Could you provide an example of what this would look like from the command line? Thanks!

**Comment by fhuonder** [comment]
Maybe like this:

`jwt .. --payload aud=["abc", "efg, "hjk] `

But I think other cases should also be possible. For example when using firebase a token could also contain such a structure
```
"firebase": {
        "identities": {
            "email": [
                "xyz@example.com"
            ],
            "google.com": [
                "1234567890123456789012"
            ]
        },
        "sign_in_provider": "google.com"
    },
```
for this, maybe a json could be provided as string?

`jwt ... --payload firebase="{any needed strucutre}"`

Due to the fact that an array is also a valid json the aud case could also be handled the same way.

Regards,
Florian

**Comment by fhuonder** [comment]
Or provide a possibility to load the whole json from a file/string? and sign it with a key.

**Comment by mike-engel** [comment]
@fhuonder In this case, the JSON payload should be passed in directly, rather than use the `--payload` arg. For you, that would look something like this:

```sh
jwt encode --secret 123 '{"firebase":{"identities":{"email":["xyz@example.com"],"google.com":["1234567890123456789012"]},"sign_in_provider":"google.com"}'
```

If I've missed something in your use case, let me know and I'll re-open.
