### ISSUE TITLE
Using openssl generated ECDSA key

### ISSUE THREAD

**Issue by flanfly** [mike-engel/jwt-cli#104]
### Summary
Hi, I (unsuccessfully) tried to encode a JWT using a ECDSA private key generated with openssl.

### Steps to reproduce
```bash
openssl ecparam -name secp256r1 -genkey -outform der > key.der
jwt encode -A ES256 -S @key.der
Something went awry creating the jwt

InvalidEcdsaKey
```
Same with PEM encoding:
```bash
openssl ecparam -name secp256r1 -genkey -outform pem > key.pem
jwt encode -A ES256 -S @key.pem
Something went awry creating the jwt

InvalidEcdsaKey
```

### Expected behavior
jwt-cli generates a JWT.

**Comment by mike-engel** [comment]
@flanfly I believe this is an issue with [jsonwebtoken](https://github.com/Keats/jsonwebtoken), one of the dependencies for this project. As of right now, [it only supports PKCS8 ES tokens](https://github.com/keats/jsonwebtoken#convert-sec1-private-key-to-pkcs8).

If you don't think that's the root issue, let me know and I'll take a look into it further!
