### ISSUE TITLE
Unsuccessful with the Windows release

### ISSUE THREAD

**Issue by pmaunu** [mike-engel/jwt-cli#11]
### Summary
I am new to JWT so it might be that I am just not using the utility in a proper way. Anyhow, I downloaded the latest Windows release and did not have success so far.

### Steps to reproduce

I run the command:
jwt encode --alg RS256 --payload '{"userName":"foobar"}' -S @decrypted-private.pem

It gave error message: 
error: Invalid value for '--payload <payload>...': payloads must have a key and value in the form key=value 

This is odd, as the JSON should be with colon?

Then I run it like this:
jwt encode --alg RS256 --payload '{"userName"="foobar"}' -S @decrypted-private.pem 

And it says:
Something went awry creating the jwt
Invalid RSA key

The decrypted-private.pem is a decrypted version of the 2048 bit RSA private key I generated with OpenSSL. 

### Expected behavior

Would be happy to be able to encode the jwt.

**Comment by mike-engel** [comment]
Hi @pmaunu, thanks for using this tool! The `-P`/`--payload` flag is for adding payload objects one by one. If you want to encode a JSON string, you can just add it to the end of the command. For your example, that would look like so:

```sh
```

**Comment by pmaunu** [comment]
Hi @mike-engel, and big thanks for your reply!

I tried what you suggested:
`jwt encode --alg RS256 -S @decrypted-private.pem '{"userName": "foobar"}'`

but this time got: 
error: Found argument 'foobar}'' which wasn't expected, or isn't valid in this context

Then, I removed the space after colon in the JSON:
`jwt encode --alg RS256 -S @decrypted-private.pem '{"userName":"foobar"}'`

and this time I got: 
thread 'main' panicked at 'Invalid JSON provided!', src/main.rs:354:18
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: BaseThreadInitThunk
   8: RtlUserThreadStart

**Comment by mike-engel** [comment]
@pmaunu I just tested this on my windows machine, and I think on windows the way to escape JSON is a little different than on macOS or linux. This is should work for you:

```sh
 jwt encode --alg RS256 -S @decrypted-private.pem "{\"userName\": \"foobar\"}"
```

Let me know if that still gives you trouble.
