### ISSUE TITLE
Remove "--prn" option or make it optional on encode

### ISSUE THREAD

**Issue by erhhung** [mike-engel/jwt-cli#114]
### Summary

According to the latest JWT spec (https://tools.ietf.org/html/rfc7519#page-9), the "`prn`" claim is not even mentioned, and according to an earlier JWT draft spec (https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-05#page-9), the "`prn`" claim is optional.

### Steps to reproduce

On encode, I get an error that the "`--prn`" required argument was not provided:
```
error: The following required arguments were not provided:
    --prn <principal>

USAGE:
    jwt encode --alg <algorithm> --aud <audience> --exp <expires> --iss <issuer> --payload <payload>... --prn <principal> --secret <secret> --sub <subject>
```

### Expected behavior

The "`--prn`" option should either be removed entirely or at least be made optional.

**Comment by kljensen** [comment]
@erhhung I didn't experience that argument as required. Can you post an example usage?

**Comment by erhhung** [comment]
The version I ran was v3.2.1 as that was the latest published in Homebrew (and still is).
I just manually pulled down v3.3.0 and ran my example again, and I still see the issue:

```bash
./jwt --version
jwt 3.3.0
```
Full example:
```bash
$ ./jwt encode \
  --iss https://foo.com \
  --aud https://bar.com \
  --sub john.doe \
  -P "jti=$(uuidgen)" \
  -P "email=john.doe@foo.com" \
  --exp "+1 hr" \
  --secret secret

error: The following required arguments were not provided:
    --prn <principal>

USAGE:
    jwt encode --alg <algorithm> --aud <audience> --exp <expires> --iss <issuer> --prn <principal> --secret <secret> --sub <subject>
```
Minimal example:
```bash
$ ./jwt encode --aud https://bar.com --secret secret

error: The following required arguments were not provided:
    --prn <principal>

USAGE:
    jwt encode --alg <algorithm> --aud <audience> --exp <expires> --prn <principal> --secret <secret>
```
Full example **without `--aud`** option:
```bash
$ ./jwt encode \
  --iss https://foo.com \
  --sub john.doe \
  -P "jti=$(uuidgen)" \
  -P "email=john.doe@foo.com" \
  --exp "+1 hr" \
  --secret secret

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGZvby5jb20iLCJleHAiOjE2MTMxNTI1NjUsImlhdCI6MTYxMzE0ODk2NSwiaXNzIjoiaHR0cHM6Ly9mb28uY29tIiwianRpIjoiMzUwOWNkNjgtNTI3OC00NmRlLTllODQtZmVjYzAyM2I0NGE2Iiwic3ViIjoiam9obi5kb2UifQ.0BKPhlWe41JVX_7mOLrAJJ1SfW1aAOcLw1P3y05psKU
```

**Comment by mike-engel** [comment]
Thanks @erhhung! I'm not sure which spec I read when I first created this tool, but `prn` was required if `aud` was present at the time. According to the current spec that you mentioned, however, it doesn't even seem to be specified. I'll remove it.

**Comment by mike-engel** [comment]
Removed in 4.0.0
