### ISSUE TITLE
Add "--jti" option to the encode command

### ISSUE THREAD

**Issue by erhhung** [mike-engel/jwt-cli#115]
### Summary

The "`jti`" claim is a registered claim name in the latest JWT spec (https://tools.ietf.org/html/rfc7519#page-10), and is used often enough that there should be an option for it in the encode command.

### Steps to reproduce

Missing "`--jti`" option in `jwt help encode`.

### Expected behavior

While it's possible to treat it as a custom claim with `--payload "jti=some_id"`, it should be supported as a first-class option.

**Comment by mike-engel** [comment]
Released with 4.0.0
