### ISSUE TITLE
fails to read secret file with absolute path

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [mike-engel/jwt-cli#118]
### Steps to reproduce

```
Step #1: + ls -lash /workspace/bazel-bot-github-key.pem
Step #1: 4.0K -rw-r--r-- 1 root root 1.7K Feb  1 18:22 /workspace/bazel-bot-github-key.pem
Step #1: ++ jwt encode --secret /workspace/bazel-bot-github-key.pem --iss 97063 --exp '+10 min' --alg RS256
Step #1: thread 'main' panicked at 'Unable to read file workspace/bazel-bot-github-key.pem', src/main.rs:321:44
Step #1: stack backtrace:
Step #1:    0: rust_begin_unwind
Step #1:              at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
Step #1:    1: std::panicking::begin_panic_fmt
Step #1:              at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
Step #1:    2: jwt::slurp_file::{{closure}}
Step #1:    3: jwt::main
Step #1: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I suspect the `.skip(1)` is the cause,
https://github.com/mike-engel/jwt-cli/blob/04669e3206d0feca72108f986305f09f44f2b647/src/main.rs#L330
but the .skip(1) must be doing something useful that I don't understand.

**Comment by xtroncode** [comment]
@SurferJeffAtGoogle 

try this 
`jwt encode --secret @/workspace/bazel-bot-github-key.pem --iss 97063 --exp '+10 min' --alg RS256`

the docs mention to use `@` while refering a file

```
 -S, --secret <secret>         the secret to sign the JWT with. Can be prefixed with @ to read from a binary file
```

it seems skipping `@` is what `.skip(1)` is doing

**Comment by mike-engel** [comment]
@SurferJeffAtGoogle @xtroncode has that correct—`jwt` looks for the presence of an `@` sign to signal that the file system should be used. We could probably do a better job of detecting file inputs, but for now, using an `@` in front of the path should do it for you. If not, please let me know and I'll re-open the issue!

**Comment by SurferJeffAtGoogle** [comment]
That worked!  Thanks.
