### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by 1995parham** [mike-engel/jwt-cli#139]
### Summary
I have created an [AUR package](https://aur.archlinux.org/packages/jwt-cli-bin/) for jwt-cli which can be installed with:

```sh
yay -Sy jwt-cli-bin
```

**Comment by mike-engel** [comment]
Thanks @1995parham! Will you be maintaining the AUR package?

**Comment by 1995parham** [comment]
I use `jwt-cli` in my daily works so I can maintain it. Also we can add this badge into repository: https://repology.org/project/jwt-cli/versions

**Comment by mike-engel** [comment]
@1995parham I would be happy to accept a PR to add install information for the AUR package! Since we don't have badges for any other package managers, I'd prefer to leave it out.

Thanks for maintaining it!
