### ISSUE TITLE
Cannot use systemd.time strings in the past (for nbf)

### ISSUE THREAD

**Issue by mark-rushakoff** [mike-engel/jwt-cli#163]
### Summary

I needed to set the nbf on my JWT a couple seconds in the past to account for clock drift, and I couldn't achieve it through the native `jwt` command line. I had to resort to arithmetic in bash (e.g. `jwt --nbf "$(( $(date +%s) - 3 ))"`).

### Steps to reproduce

```console
$ jwt --version
jwt 5.0.0

$ # Notice that the printed date matches iat, and nbf == iat+5, not iat-5.
$ date +%s; jwt encode --secret foo --nbf='5 seconds ago' | jwt decode -
1641934457

Token header
------------
{
  "typ": "JWT",
  "alg": "HS256"
}

Token claims
------------
{
  "iat": 1641934457,
  "nbf": 1641934462
}

$ jwt encode --secret foo --nbf='-5s'
error: Invalid value for '--nbf <not_before>': must be a UNIX timestamp or systemd.time string
```

### Expected behavior

I thought `-5s` would be accepted and calculated properly. When that wasn't, then I tried `5 seconds ago`, which was accepted, but calculated incorrectly.

I believe [`man 7 systemd.time`](https://www.man7.org/linux/man-pages/man7/systemd.time.7.html) says that either of those formats should be accepted:

> When parsing, systemd will also accept relative time
> specifications. A time span (see above) that is prefixed with "+"
> is evaluated to the current time plus the specified time span.
> Correspondingly, a time span that is prefixed with "-" is
> evaluated to the current time minus the specified time span.
> Instead of prefixing the time span with "+" or "-", it may also
> be suffixed with a space and the word "left" or "ago".

**Comment by mike-engel** [comment]
This should be fixed now in `5.0.2`, thanks for the report and your patience @mark-rushakoff!
