### ISSUE TITLE
Not working on alpine linux

### ISSUE THREAD

**Issue by ukreddy-erwin** [mike-engel/jwt-cli#194]
I tried installing this on a docker container, alpine linux.

`docker run -it alpine:3.6`

And ran below set of commands.

`wget https://github.com/mike-engel/jwt-cli/releases/download/5.0.3/jwt-linux.tar.gz;tar -xvzf jwt-linux.tar.gz;rm -rf jwt-linux.tar.gz;mv jwt /usr/local/bin/`

But, when I ran jwt, getting error as not found.
.usr/local/bin is already in system path.

Even from current working directory also same issue.

```
./jwt
/bin/sh: ./jwt: not found
```

**Comment by mike-engel** [comment]
I'm not sure that this is an issue with `jwt-cli` specifically? This seems like an issue with the docker setup or alpine linux where it can't find the executable. `jwt-cli` has no concept, as far as I know, about its environment and definitely doesn't call itself during execution. Could this be a permissions issue? `chmod +x /usr/local/bin/jwt`?

**Comment by mike-engel** [comment]
Sorry, I assumed this wasn't a problem with the `jwt` binary.

Upon further inspection, alpine linux seems to require a static binary (not dynamically linked). This would require rust to be built with the `musl` target, but unfortunately `ring`, which is a transitive dependency of `jsonwebtoken` doesn't support static linking: https://github.com/briansmith/ring/issues/713

Until `ring` supports static linking via the `musl` target, `jwt` won't be able to run on alpine linux. Sorry! I'll leave this issue open for now though

**Comment by tomwiggers** [comment]
Hi, I think this needs to be documented because I now spent a few hours facing the same issue on a busybox container with the most recent version.

Basically using the same method as OP. It is also not possible to pass it was argument to `sh`:
```
$ sh jwt
jwt: line 1: syntax error: unexpected "("
```

**Comment by mike-engel** [comment]
Added a note with 10cea20. Thanks all!

**Comment by FollieHiyuki** [comment]
Hi! Just let you know that I'm making an attempt to package `jwt-cli` for AlpineLinux at https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/46338.

It already works on my machine after the build. If the MR gets merged, you can install the package directly from Alpine's `edge` repo.

**Comment by Rogach** [comment]
FYI - currently builds without issues with x86_64-unknown-linux-musl target and rustc 1.77.0-nightly (only had to update proc-macro2 dependency to avoid the `unknown feature proc_macro_span_shrink` error).

**Comment by ajschmidt8** [comment]
> Sorry, I assumed this wasn't a problem with the `jwt` binary.
> 
> Upon further inspection, alpine linux seems to require a static binary (not dynamically linked). This would require rust to be built with the `musl` target, but unfortunately `ring`, which is a transitive dependency of `jsonwebtoken` doesn't support static linking: [briansmith/ring#713](https://github.com/briansmith/ring/issues/713)
> 
> Until `ring` supports static linking via the `musl` target, `jwt` won't be able to run on alpine linux. Sorry! I'll leave this issue open for now though

The linked `ring` issue seems resolved now.

Can this issue be revisited to support Alpine?

**Comment by mike-engel** [comment]
I've now included a `musl` build as part of the release process. Hope this is what y'all are looking for, and if not, please let me know here. Thanks!
