### ISSUE TITLE
Unintuitive syntax / error message for RSA secret

### ISSUE THREAD

**Issue by takesson** [mike-engel/jwt-cli#208]
It was not immediately clear to me that the RSA key had to be read from file and then why it stripped the leading character from the path (regardless which character).

I think it would help to have the "if first character is @" and display an error message in the else clause. This ensures that only '@' is eligible to strip.

https://github.com/mike-engel/jwt-cli/blob/9b8f6c967e5216101f6eba7847adddb90aa839f5/src/main.rs#L353

Thanks for a great tool!

**Comment by takesson** [comment]
Related to #162

**Comment by fredrikwangberg** [comment]
+1 I also stumbled upon this. My file was called `private.pem` and the error message said `thread 'main' panicked at 'Unable to read file rivate.pem'`, which makes no sense.

**Comment by mike-engel** [comment]
Error message will be displayed in the next version with 3e2fb9f. Thanks for bringing this up!
