### ISSUE TITLE
brew upgrade: Please update to Xcode 14.1 (or delete it). But 14.1 is not released yet

### ISSUE THREAD

**Issue by raarts** [mike-engel/jwt-cli#213]
### Summary

Why does it require an Xcode version that isn't released yet?

The brew package says: 

```
==> Upgrading mike-engel/jwt-cli/jwt-cli
  5.0.0 -> 5.0.3

Error: Your Xcode (14.0.1) is too outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.

```
### Steps to reproduce

brew upgrade jwt-cli

**Comment by mike-engel** [comment]
@raarts I don't have any dependency on xcode, nor do I use it for this project at all. Does this happen with any other packages for you on your machine?

**Comment by raarts** [comment]
Ok, I found this: https://github.com/Homebrew/homebrew-core/issues/113968#issuecomment-1290752564
I'll have to wait for 14.1 to come out I guess. Sorry for bothering you with this.

**Comment by mike-engel** [comment]
No worries, hope that they publish a fix soon!
