### ISSUE TITLE
Provide a container image for jwt-cli

### ISSUE THREAD

**Issue by lewandom** [mike-engel/jwt-cli#218]
Ideally, a scratch image, so no worries of updating the base operating system. Expected usage: Tekton tasks.
Here's a sample Dockerfile I created for my own purposes, however I believe it can be organized better into the existing build process instead of building stuff inside a multi-stage Dockerfile:

```
FROM docker.io/rust:1-alpine as build
ARG JWT_CLI_VERSION
ARG JWT_CLI_DOWNLOAD_BASE=https://github.com/mike-engel/jwt-cli/archive/refs/tags
RUN set -eux \
 && wget -nd ${JWT_CLI_DOWNLOAD_BASE}/${JWT_CLI_VERSION}.tar.gz \
 && tar xf ${JWT_CLI_VERSION}.tar.gz
WORKDIR /jwt-cli-${JWT_CLI_VERSION}
RUN set -eux \
 && apk add --no-cache musl-dev \
 && rustup target add x86_64-unknown-linux-musl \
 && cargo build --release --target=x86_64-unknown-linux-musl \
 && cp ./target/x86_64-unknown-linux-musl/release/jwt /

FROM scratch
COPY --from=build /jwt /
ENTRYPOINT ["/jwt"]
CMD ["-h"]
```

**Comment by mike-engel** [comment]
Hey @lewandom, thanks! This is unfortunately something I'm not really interested in creating/maintaining long-term. If you'd like to create and own a dockerfile in this repository, I can think about publishing it to docker hub, otherwise I'll probably leave this to the community
