### ISSUE TITLE
GoFish has been abandoned and documentation about it in the README should be removed

### ISSUE THREAD

**Issue by adamency** [mike-engel/jwt-cli#228]
`gofish` development has been stopped, the repo on github has been archived (https://github.com/fishworks/gofish) and the 'go.fish' domain isn't registered anymore.

I advise maintainers to remove any documentation about installing `jwt-cli` through it, and most importantly to remove the mention of above-mentioned domain in order to prevent phishing issues in case the domain is bought back for malicious motives.

**Comment by mike-engel** [comment]
Thanks for the notice @adamency!

**Comment by mike-engel** [comment]
Very sorry for the delay, but this is in [6.0.0](https://github.com/mike-engel/jwt-cli/releases/tag/6.0.0) now
