### ISSUE TITLE
Tests not in `main_test.rs' don't run

### ISSUE THREAD

**Issue by jazcarate** [mike-engel/jwt-cli#237]
### Summary
Tests that are not in ``main_test.rs` don't run when doing `cargo test` (so also the CI)

### Steps to reproduce
1. Add a test that fails in any test file.
2. Run `$ cargo test`
```rust
#[test]
fn foo() {
    assert_eq!(1, 2);
}
```

### Expected behavior
A test should fail.
Instead you get
> test result: ok. 23 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.08s

**Comment by mike-engel** [comment]
Thanks for the heads up @jazcarate!
