### ISSUE TITLE
linux binary for jwt 5.0.3 does not run on CentOS 7

### ISSUE THREAD

**Issue by TJM** [mike-engel/jwt-cli#263]
### Summary

Doesn't run on centos 7

### Steps to reproduce

* jwt help

```
$ jwt help
jwt: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by jwt)
jwt: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by jwt)
jwt: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by jwt)
jwt: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by jwt)
```

### Expected behavior

runs ;)

**Comment by TJM** [comment]
I don't I was just helping someone do the jwt decode on their jump server, and it didn't run, do you have a suggestion for which version to try? It looks like we need 2.17?

```
$ rpm -qa | grep glibc
glibc-common-2.17-325.el7_9.x86_64
glibc-headers-2.17-325.el7_9.x86_64
glibc-devel-2.17-325.el7_9.x86_64
glibc-2.17-325.el7_9.x86_64
glibc-2.17-325.el7_9.i686
```

**Comment by TJM** [comment]
FYI, we also tried to compile the source (definitely not a developer) :p 

```
   Compiling anstyle-query v1.0.0
   Compiling serde_json v1.0.96
   Compiling anstream v0.3.0
error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/tmcneely/Projects/jwt-cli/target/debug/deps/libserde_derive-db02c9296cd10d4e.so)
   --> /home/tmcneely/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.147/src/lib.rs:305:1
    |
305 | extern crate serde_derive;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling aho-corasick v0.7.19
error[E0432]: unresolved imports `self::__private`, `self::__private`
   --> /home/tmcneely/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.147/src/lib.rs:287:5
    |
287 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^
288 | #[allow(unused_imports)]
289 | use self::__private as private;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0432`.
error: could not compile `serde` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

Same sort of error, something is trying to require GLIBC 2.18

**Comment by TJM** [comment]
Hah, nice idea, but the whole point of Enterprise Linux is to have an ABI that doesn't change. So vendors can release a binary that should work without having to worry about a bunch of shared stuff ;). A static linked binary might work, but they could also upgrade to RHEL8. I will have them try some older versions too.

**Comment by mike-engel** [comment]
This project has used serde since the beginning, so I'm pretty sure no previous version will work, but I'll be eager to hear if a particular version broke at some point.

**Comment by mike-engel** [comment]
Hmm looking at the diff, it looks like maybe a transitive dependency update of `ring` via `jsonwebtoken`. It also looks like I had problems with CI and gcc. Either way, probably not something I can personally do, so I'm going to close this now with the workaround you provided, unless someone else can devote time to debugging this up the chain.

Thanks for reporting and finding the workaround @TJM!
