### ISSUE TITLE
Add support for TTL when generating JWTs

### ISSUE THREAD

**Issue by stephent** [mike-engel/jwt-cli#268]
Thanks for this tool! It would be great to be able to use a --ttl option, instead of -exp, to specify the number of seconds in which the new token should expire relative to current system time, e.g.

```
jwt encode '{ "tokenIsvalidFor": "15 minutes }' --ttl=900 --secret=[SECRET]
```

**Comment by rostamn739** [comment]
You mean something like this?

https://github.com/mike-engel/jwt-cli/compare/main...rostamn739:jwt-cli:main

**Comment by stephent** [comment]
Ah ok - didn't get that from the docs, but that's perfect.
