### ISSUE TITLE
superfluous output on stdout doesn't help programmatic usage

### ISSUE THREAD

**Issue by docteurklein** [mike-engel/jwt-cli#3]
### Summary

Having displayed 
```
Success! Here's your token                                                                                                                                                  

```
on stdout seems superfluous. Maybe it shouldn't be displayed at all (or stderr at least), and should return 0 or 1 in case of success or failure respectively, thus following more the UNIX philosophy.

That would allow me to do stuff like:

    TOKEN=$( jwt encode -S 'secret' -P role=todo_user)

### Steps to reproduce

    jwt encode -S 'secret' -P role=todo_user
    Success! Here's your token
                                                                                                                                                  
    <SOME-TOKEN-OUTPUT>

### Expected behavior

    jwt encode -S 'secret' -P role=todo_user
    <SOME-TOKEN-OUTPUT>

Thanks for this CLI! awesome.

**Comment by mike-engel** [comment]
Glad to hear you’re liking it! So I assume you’re trying to pipe the output or spawn a child process and intercept STDOUT? If so, I can go ahead and remove that or hide it behind a flag. I’ll have to check how rust sends exit codes though to emit a 0 on success. Thanks!

**Comment by mike-engel** [comment]
(Whoops didn’t see your example 😅)

**Comment by docteurklein** [comment]
thanks for the quick answer! I added the example afterwards, so that may be it :) 

I tried to have a look at https://stackoverflow.com/a/30285110/244058 and https://doc.rust-lang.org/std/process/fn.exit.html and wanted to try a PR, but I never edited rust code, so yeah.

**Comment by mike-engel** [comment]
No worries! If you’d like to attempt a PR, let me know and I’d be happy to review the PR. Otherwise, I’ll try and take care of it this week.

**Comment by mike-engel** [comment]
I'm stuck on a plane, so I went ahead and took care of this. 1.2.0 should resolve this with simplified output for `encode`, and explicit exit codes! Travis is a bit backed up on macOS builds right now if you need that, but linux and windows builds are up 😄

**Comment by docteurklein** [comment]
@mike-engel awesome! thanks a lot :)
