### ISSUE TITLE
Bump jsonwebtoken to v8.3.0 to v9.x.x

### ISSUE THREAD

**Issue by marcb** [mike-engel/jwt-cli#302]
### Summary
Building for aarch64-pc-windows-msvc breaks due to ring v0.16.0 via jsonwebtoekn v8.3.0. Ring fix starts with v9.0.0

```
cargo tree -p ring -i
ring v0.16.20
└── jsonwebtoken v8.3.0
    └── jwt-cli v6.0.0 (/Users/marc/src/oss/jwt-cli)
```

### Steps to reproduce
On Windows 11 on AARCH64 machine with rustup 1.26.0 (5af9b9484 2023-04-05), rustc 1.74.0 (79e9716c9 2023-11-13), cargo 1.74.0 (ecb9851af 2023-10-18). Installing via `cargo install jwt-cli` - ring has build failures. See ring issue https://github.com/briansmith/ring/issues/1167 for background.

### Expected behavior
With a jsonwebtoken version >= 9.0.0 it should build and install.

**Comment by mike-engel** [comment]
PR: #296. I haven't had time to do the upgrade yet. If anyone would like to take a stab at it, I'm happy to review PRs 😄

**Comment by mike-engel** [comment]
Done as of https://github.com/mike-engel/jwt-cli/pull/311
