### ISSUE TITLE
Brew formula does not work with linuxbrew

### ISSUE THREAD

**Issue by jamesphillpotts-fr** [mike-engel/jwt-cli#309]
### Summary

The formula for jwt-cli in brew installs the macos version even when using [linuxbrew](https://docs.brew.sh/Homebrew-on-Linux). Using the install from source option also does not appear to work.

### Steps to reproduce

On linux: `brew install mike-engel/jwt-cli/jwt-cli`

### Expected behavior

The linux binary and SHA should be used instead of the macos one.

**Comment by mike-engel** [comment]
Thanks for the report @jamesphillpotts-fr. Unfortunately I don't use linuxbrew, and don't have the time to work on a fix for this at the moment. If anyone has time, I'd love to review any PRs!

**Comment by mike-engel** [comment]
@jamesphillpotts-fr I believe this is fixed with https://github.com/mike-engel/homebrew-jwt-cli/pull/2 now.
