### ISSUE TITLE
Publish to Cargo?

### ISSUE THREAD

**Issue by therealklanni** [mike-engel/jwt-cli#33]
Please `cargo publish` this package? Looks like the Cargo.toml is good-to-go, just needs a publish. 

This would make it possible to install via `cargo install jwt-cli` on any platform where `cargo` exists.

After publishing, I'm willing to update the README install section to detail the `cargo install` option.

**Comment by mike-engel** [comment]
Great idea! I've just published it to cargo. I would love to have a PR from you since I don't have a ton of time lately. Once that comes through I'll merge it in.

**Comment by therealklanni** [comment]
Thanks! PR on the way.
