### ISSUE TITLE
Parsing fails on token with no `typ` attribute in header.

### ISSUE THREAD

**Issue by bsberry** [mike-engel/jwt-cli#4]
### Summary
With a token with the `alg` specified in the header but no `typ`, I get the following error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Json(ErrorImpl { code: Message("missing field `typ`"), line: 1, column: 15 }), State { next_error: None })', src/libcore/result.rs:859`

### Steps to reproduce

`jwt decode eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.SEQijh6tEuOOAAKpHPuKxgFqEvlTNP1jj4FUNoBwXaM`

### Expected behavior
It should decode and display.

**Comment by mike-engel** [comment]
@bsberry the upstream crate I use for jwt decoding made `typ` optional, but now requires the secret to be known ahead of time. I'm assuming you don't always know the secret, but wanted to check if that would be ok for you? Thanks

**Comment by shousper** [comment]
I would be totally okay with this if that helps? :) Handy to be able to see what's in the JWT easily without having to verify and/or have all the standard attributes ;)

Maybe output something to `stderr` when something is a bit broken?

#my2cents

**Comment by mike-engel** [comment]
I've released 2.0.0, which should allow you to parse a jwt without a `typ` header. Thanks!
