### ISSUE TITLE
Panic with command 'jwt decode help' command

### ISSUE THREAD

**Issue by brandonfoltzclarivate** [mike-engel/jwt-cli#50]
### Summary
When invalid order of parameters are supplied: ```jwt decode help``` the program panics with error

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(InvalidToken)', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Obviously not a huge issue but maybe not the expected behavior.

### Steps to reproduce
See summary

### Expected behavior
A more helpful error message be printed.

**Comment by mike-engel** [comment]
So unfortunately due to clap-rs/clap#1350, I can't provide the help documentation on a subcommand. I can, however, prevent the command from panicking, which is what the next version will do. Thanks for the report!
