### ISSUE TITLE
"invalid RSA key" when using RS256

### ISSUE THREAD

**Issue by felschr** [mike-engel/jwt-cli#56]
### Summary
When I try to encode a JWT using RS256 I get the following error:
```
Something went awry creating the jwt

invalid RSA key
```

### Steps to reproduce
I've run the following command on a Linux machine (NixOS):
```
jwt encode --alg RS256 --secret key.pem '{"iss": "ISSUER", "aud": "AUDIENCE"}'
```

The same command with default algorithm of HS256 is working:
```
jwt encode --secret key.pem '{"iss": "ISSUER", "aud": "AUDIENCE"}'
```

I've tried it both with an RSA PEM key using pkcs1 (`BEGIN RSA PRIVATE KEY`) and pkcs8 (`BEGIN PRIVATE KEY`):

### Expected behavior

JWT is successfully created using RS256 algorithm.

**Comment by mike-engel** [comment]
Thanks for the report @FelschR! Looking at [the tests](https://github.com/mike-engel/jwt-cli/blob/7a62da177472fb89bbf2b622e000f45fa9a6c0db/tests/jwt-cli.rs#L402) (I think RSA was added as a PR by someone else), it looks like we have [special syntax to slurp the file](https://github.com/mike-engel/jwt-cli/blob/7a62da177472fb89bbf2b622e000f45fa9a6c0db/src/main.rs#L318). Can you try again with the following command?

```sh
jwt encode --alg RS256 --secret @key.pem '{"iss": "ISSUER", "aud": "AUDIENCE"}'
```

The second example you have with the default `alg` makes sense because it's treating `key.pem` as a string and not expecting a file

**Comment by glacials** [comment]
For posterity I ran into the same issue using an `RS256` private key file with the extension `.key` (and using the `@`-slurping syntax), but changing its extension to `.pem` fixed the issue.

**Comment by mike-engel** [comment]
Closing this since I don't think there's an issue here. If there still is, please feel free to reopen.

**Comment by glacials** [comment]
I'm not OP and I'm still not sure if the workaround I mentioned is directly related to the issue they were having. But I do think that at minimum there should be a helpful error message about file extensions, and ideally the file extension shouldn't matter -- I think most people think of file extensions only as a signal to the OS what program it should open a file with. It was almost by chance that I found that that was the issue.

**Comment by mike-engel** [comment]
@glacials I don't know how soon I'll be able to get to this. If you'd like to, I'd be happy to review a PR. Thanks!

**Comment by edobry** [comment]
I just ran into the same thing and couldn't figure out what was wrong until coming across this issue; some documentation or an error message would be great!

Thanks for the great tool btw, I've found it quite helpful.

**Comment by Georift** [comment]
Also just ran into this, some warning about it not being `.pem` would be nice.

**Comment by freudl** [comment]
Sorry to reopen, but I think there remains an issue passing the private key.

Using `@filename` notation works perfectly. Passing the key as value, however, does not for me.

```bash
++ jwt encode --alg RS512 --kid dummy --exp=1737207582 --secret '-----BEGIN RSA PRIVATE KEY-----
MI…GF/f0=
-----END RSA PRIVATE KEY-----' '{"hello":"world"}'
error: unexpected argument '-----BEGIN RSA PRIVATE KEY-----
MI…GF/f0' found

  tip: to pass '-----BEGIN RSA PRIVATE KEY-----
MI…GF/f0' as a value, use '-- -----BEGIN RSA PRIVATE KEY-----
MI…GF/f0'

Usage: jwt encode …

For more information, try '--help'.
```

I think, that's related to the value starting with dash which seems to confuse the argument parser.

Which option do you suggest to use a secret starting with dash?
