### ISSUE TITLE
Incorrect version when upgrading to v3.0.0

### ISSUE THREAD

**Issue by ErickStaal** [mike-engel/jwt-cli#60]
### Summary
after upgrading via _cargo install jwt-cli_ and giving the command ./jwt -V in ~/.cargo/bin the version is still v2.5.1 instead of the expected v3.0.0

### Steps to reproduce
see summary. Platform is Fedora 31 amd64.

### Expected behavior
see summary.

**Comment by mike-engel** [comment]
Hi @ErickStaal, thanks for the issue! It looks like when I pushed up my changes the tag went up but not the actual code. It should work now. If not, let me know!

**Comment by ErickStaal** [comment]
Hi Mike,

when working from the source code tar.gz file still v2.5.1 pops up when performing a ./jwt -V from ~/.cargo/bin

**Comment by mike-engel** [comment]
@ErickStaal Forgot to publish to crates.io! 3.0.0 and 3.0.1 should both be live now 😄
