### ISSUE TITLE
Release v3.0.* is missing binaries for linux 

### ISSUE THREAD

**Issue by fmotrifork** [mike-engel/jwt-cli#61]
First of, thank you for this great tool! I really love it, and use it often.

### Summary
The two newest releases does not contain the Linux binaries.

`jwt-cli` is avaible through the gofish package manager here:
https://github.com/fishworks/fish-food/blob/master/Food/jwt-cli.lua

But I am not able to add the newest release to this, as the linx bin is missing.

### Expected behavior
I would expect all releases to have binaries for all OS.

**Comment by mike-engel** [comment]
@fmotrifork Sorry about that! I recently wiped my linux computer and CI/CD isn't fully set up for linux, so I forgot to do that. They're uploaded now. Let me know if it's still not working!
