### ISSUE TITLE
Support for piped input would be nice

### ISSUE THREAD

**Issue by bobobox** [mike-engel/jwt-cli#69]
### Summary
I'm finding this utility helpful for debugging JWTs that I'm getting via a pipeline starting with `curl`, going though `jq` to extract the JWT, and then sending to `jwt-cli`. Right now I have to stick `xargs` in there to provide `jwt-cli` with the JWT as an argument. It would be nice if it could just accept piped input.

### Steps to reproduce
 
    $ curl <curl stuff to auth API> | jq -r .access_token | jwt decode
    error: The following required arguments were not provided:
       <jwt>

Instead I have to do:

    $ curl <curl stuff to auth API> | jq -r .access_token | xargs jwt decode

### Expected behavior:

`jwt-cli` detects JWT input via STDIN, like in the first case above, and handles it

**Comment by mike-engel** [comment]
Thanks for the issue! This might not be documented anywhere, which is on me, but using a `-` will tell `jwt-cli` to read from `stdin`. This should do it for you. If not, let me know and I'll treat this as a bug.

```sh
curl <curl stuff to auth API> | jq -r .access_token | jwt decode -
```

This worked for me as a quick test:
```sh
jwt encode --secret=fake '{"admin":false,"test":{"stuff":"things","s": "t"}}' | jwt decode -
```

**Comment by bobobox** [comment]
Ah, thanks for the tip! Yes, it works fine for me with the `-`.
