### ISSUE TITLE
Doesn't properly encode nested records

### ISSUE THREAD

**Issue by JasonMFry** [mike-engel/jwt-cli#7]
### Summary

Using nested records doesn't get encoded properly.

### Steps to reproduce

Run `jwt encode -e 1539178753 -n 0 -S "fake" -P admin=false, test:{stuff=things,s=t}`

### Actual Behavior

```json
Token claims
------------
{
  "admin": "false,",
  "exp": 1539178753,
  "iat": 1539179624,
  "nbf": 0,
  "test:s": "t",
  "test:stuff": "things"
}
```

### Expected behavior

```json
Token claims
------------
{
  "admin": "false,",
  "exp": 1539178753,
  "iat": 1539179624,
  "nbf": 0,
  "test": {"s": "t", "stuff": "things"}
}
```

**Comment by mike-engel** [comment]
Hey @JasonMFry! Thanks for reporting this. It looks like, however, your syntax is a little off. The way that `jwt-cli` supports objects is via a JSON string. My shell is fish so I have to put quotes around it, but this is how I got your token:
```sh
jwt encode -e 1539178753 -n 0 -S "fake" -P admin=false -P 'test={ "stuff": "things", "s": "t" }'

// eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTUzOTE3ODc1MywiaWF0IjoxNTM5MTgzMzcwLCJuYmYiOjAsInRlc3QiOnsicyI6InQiLCJzdHVmZiI6InRoaW5ncyJ9fQ.lOrVPkgN-O01YpATw3ry4cth-bCLpVUqMGGiBcKvsbU
```
Decoding it looks like so:
```sh
jwt decode eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhZG1pbiI6ZmFsc2UsImV4cCI6MTUzOTE3ODc1MywiaWF0IjoxNTM5MTgzMzcwLCJuYmYiOjAsInRlc3QiOnsicyI6InQiLCJzdHVmZiI6InRoaW5ncyJ9fQ.lOrVPkgN-O01YpATw3ry4cth-bCLpVUqMGGiBcKvsbU

Token header
------------
{
  "typ": "JWT",
  "alg": "HS256"
}

Token claims
------------
{
  "admin": false,
  "exp": 1539178753,
  "iat": 1539183370,
  "nbf": 0,
  "test": {
    "s": "t",
    "stuff": "things"
  }
}
```

If you still have trouble, let me know. Thanks!

**Comment by JasonMFry** [comment]
It took us over 30 minutes of debugging and found that it absolutely doesn't take JSON, the error output even says the payload must take `key=value` which is not JSON. If it does take JSON then the error output and documentation should be updated. As it is we have begun using a different tool because of the time wasted.

**Comment by mike-engel** [comment]
@JasonMFry Thanks! I've been working on this and would like to get your opinion on two solutions.

The first allows you to add a JSON string behind a `-j` flag like so:
```sh
jwt encode -S 'fake' -j '{"test":"hello"}' 
```

The second would be added as an argument without a flag. Because of the library I'm using, however, it would require a `--` before the argument:
```sh
jwt encode -S 'fake' -P admin=True -- '{"test":"hello"}' 
```

Let me know what you think is best. Thanks!

**Comment by JasonMFry** [comment]
You said that because of the library you're using, it would require `--`, but is there a way to provide a default in your code? I imagine the most common use case would be json, but forcing the user to add a flag for the most common use case would be inconvenient and potentially error prone.

I would prefer the following:

- some random flag (let's say `-x`) uses object notation `{key: "value"}`
- no flags at all means json

If that is for some reason impossible, I would prefer `-j` because it is more memorable to me than `--`.

**Comment by mike-engel** [comment]
@JasonMFry I actually realized there was a bug in my code, so a JSON string can be the last argument without any flag. You could also augment with the `-P` or `--payload` flag if needed. So, thinking about your example above, any of these would be valid

```sh
jwt encode -e 1539178753 -n 0 -S "fake" -P admin=false '{"test":{"stuff":"things","s": "t"}}'
jwt encode -e 1539178753 -n 0 -S "fake" '{"admin":false,"test":{"stuff":"things","s": "t"}}'
jwt encode -e 1539178753 -n 0 -S "fake" -P admin=false  -P 'test={"stuff":"things","s": "t"}'
jwt encode -e 1539178753 -n 0 -S "fake" '{"admin": false, "test": { "stuff": "things", "s": "t" } }'
```

The only caveats that remain are that the JSON string is valid JSON. If not, serde (rust deserialization package) won't be able to parse it. Hopefully that makes sense and sounds good to you. Fighting with CI at the moment, but I hope to publish it soon. Thanks for working with me on this!

**Comment by JasonMFry** [comment]
Looks great! 👍

**Comment by mike-engel** [comment]
@JasonMFry If you're on windows or macOS, you can now upgrade to 2.2.0 if you still use this tool or are interested in it again. If you're on linux, I'm going to try and release that tonight. Thanks
