### ISSUE TITLE
Absent expiry is treated as expired when decoding with secret validation

### ISSUE THREAD

**Issue by glacials** [mike-engel/jwt-cli#70]
### Summary
When decoding a token with no expiry, and with secret validation on, an error message "The token has expired" is displayed, even though there is no expiration. This message is correctly not displayed when passing no `--secret`.

([RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.4) specifies `exp` as optional)

### Steps to reproduce
1. Generate a JWT with another tool with no expiration (as `jwt` does not seem to support absent expirations)
2. `jwt decode --secret THE_SECRET THE_TOKEN`
3. `jwt` reports something like
    ```
    The token has expired
    
    Token header
    ------------
    {
      "typ": "JWT",
      "alg": "HS256"
    }
    
    Token claims
    ------------
    {
      "fresh": false,
      "iat": 1588198314,
      "identity": 1,
      "jti": "c43853a6-a4f8-49ae-a8dc-5b708b833514",
      "nbf": 1588198314,
      "type": "access"
    }
    ```

### Expected behavior
I expect `jwt` to behave just like it does when calling it with `jwt decode THE_TOKEN` (no secret validation):
```

Token header
------------
{
  "typ": "JWT",
  "alg": "HS256"
}

Token claims
------------
{
  "fresh": false,
  "iat": 1588198314,
  "identity": 1,
  "jti": "c43853a6-a4f8-49ae-a8dc-5b708b833514",
  "nbf": 1588198314,
  "type": "access"
}
```

**Comment by mike-engel** [comment]
Thanks for your patience on this @glacials! This will be fixed in the next version 😄
