### ISSUE TITLE
Remove trailing newline during decode

### ISSUE THREAD

**Issue by dearchap** [mike-engel/jwt-cli#87]
### Summary
When piping the output of jwt encode to jwt decode it fails signature verification due to the newline 

### Steps to reproduce
jwt encode —secret foo ‘{ “bar” : 10 }’ | jwt decode —secret foo

### Expected behavior
It should pass signature verification 

If I store the output of jwt encode in an environment variable and pipe it with “echo -n” to jwt decode the verification is fine

**Comment by mike-engel** [comment]
@dearchap Thanks for your patience! The next update will have a fix for this when piping the stdout to something else.
