### ISSUE TITLE
Symlink not create by homebrew

### ISSUE THREAD

**Issue by Sytten** [mike-engel/jwt-cli#92]
### Summary
When trying to install via homebrew it seems like the symlink is not created properly.

### Steps to reproduce
1. Install via homebrew
2. Try `jwt help` -> command not found

### Expected behavior
Symlink is properly created

**Comment by mike-engel** [comment]
Hi @Sytten, I'm really sorry about that. `3.2.1` has just been released, and fixes the problem!
